name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Injetar chaves de API nos arquivos
        run: |
          echo "window.AUDIUS_API_KEY = '${{ secrets.AUDIUS_API_KEY }}';" > config.js
          echo "window.AUDIUS_API_SECRET = '${{ secrets.AUDIUS_API_SECRET }}';" >> config.js
          echo "window.AUDIUS_BEARER_TOKEN = '${{ secrets.AUDIUS_BEARER_TOKEN }}';" >> config.js
          echo "window.EUROPEANA_API_KEY = '${{ secrets.EUROPEANA_API_KEY }}';" >> config.js
          echo "window.GUARDIAN_API_KEY = '${{ secrets.GUARDIAN_API_KEY }}';" >> config.js
          echo "window.JAMENDO_API_KEY = '${{ secrets.JAMENDO_API_KEY }}';" >> config.js
          echo "window.NARA_API_KEY = '${{ secrets.NARA_API_KEY }}';" >> config.js
          echo "window.NASA_API_KEY = '${{ secrets.NASA_API_KEY }}';" >> config.js
          echo "window.QWEN_API_KEY = '${{ secrets.QWEN_API_KEY }}';" >> config.js
          echo "window.SPOTIFY_CLIENT_ID = '${{ secrets.SPOTIFY_CLIENT_ID }}';" >> config.js
          echo "window.SPOTIFY_CLIENT_SECRET = '${{ secrets.SPOTIFY_CLIENT_SECRET }}';" >> config.js
          echo "window.TMDB_API_KEY = '${{ secrets.TMDB_API_KEY }}';" >> config.js
          echo "window.TWITCH_CLIENT_ID = '${{ secrets.TWITCH_CLIENT_ID }}';" >> config.js
          echo "window.TWITCH_CLIENT_SECRET = '${{ secrets.TWITCH_CLIENT_SECRET }}';" >> config.js
          echo "window.VIMEO_API_KEY = '${{ secrets.VIMEO_API_KEY }}';" >> config.js
          echo "window.YOUTUBE_API_KEY = '${{ secrets.YOUTUBE_API_KEY }}';" >> config.js

      - name: Configurar Pages e Upload
        uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
